### PR TITLE
Refactor: move removeSourceComments()

### PR DESCRIPTION
**Pull request by Jonathan-J8**
Hi,

I moved the `removeSourceComments()` function from `loadChunks()` to `compressShader()` for easier debugging purposes.

My intention was to retain comments while working with the default `#include <...>` statements from Three.js. These comments help identify specific code segments when logging the shader. As a result, it becomes easier to identify shader chunks from Three.js without needing to search extensively within the source code to understand their functionalities.

Moreover, it seems more appropriate to remove comments during the compression of the shader file (production mode) rather than in the development mode.

Best regards,

### CODE REVIEW

**Comment by UstymUkhman** [comment]
Hi @Jonathan-J8! Thanks for your contribution, I can totally understand this decision, however, I need to think about it a bit more. You see, the reason for comments being removed at the beginning of the `loadChunks` function was to avoid including shader chunks like this one:

```glsl
// #include "./chunk.glsl";

void main () {
  // ...
}
```

Like in other programming languages, removing parts of code with comments is helpful during development. Another reason I'm in doubt about this decision is because `compress` option is `false` by default and your shaders will not be minified unless explicitly specified. This means by default shader comments will never be removed and commented chunk might potentially cause unexpected behavior because they will be still imported by this plugin.

Like I said, I totally get your thinking behind this choice, I just want to think more about it and find a better way to solve this issue. Thanks again for your contribution!

**Comment by Jonathan-J8** [comment]
Hello @UstymUkhman, 
I hadn't considered that before—thank you for pointing that out!

Before proceeding with this refactoring, I was implementing a `preserveComments` option within the `LoadingOptions` specifically for development purposes. This option would be `false` buy default and also `false` when `compress: true`.
However, the user have to be aware of this, due to the possible unexpected behavior you pointed out.
Perhaps this could be a better solution. What do you think ?

**Comment by UstymUkhman** [comment]
Hi again @Jonathan-J8!

It took me while, but I think I might have a good solution to this enhancement. In some languages (like TypeScript and C#) there are special comments starting with `///`. So how about we aren't going to remove those but keep them unless the `compress` option is enabled. So, to recap: `/* ... */` and `// ...` will be always removed when loading chunks. `/// ...` will be skipped at this stage and removed only if `compress: true`.

In this way, during the development, you'll be able to have things like this in your output shader:

```glsl
/// Use "rand" function from three.js:
#include <common>
```

Of course, users will have to be careful to not do stuff like this: `/// #include ./some_chunk.glsl;`, 'cause like I said above, It might cause unexpected behavior, put I think chances of doing that are pretty low... 🤞
I'm going to close this PR now, I will work on this feature this week, but please let me know what do you think about it. Cheers!

**Comment by Jonathan-J8** [comment]
Hi @UstymUkhman,

Thank you for considering this.

If I were in your position, I would not develop this feature unless there is a regex to remove the `/// #include ….` comments. If not, users need to be aware of this. Additionally, I do not know if your code handles other types of comments such as `/// // #include ….` or `, `/// /* #include…`, etc... Those are others side effects to be aware of.
I prioritise stability over features, and your plugin is completely stable at this stage.

Although my initial need was to easily understand the contents of chunks from Three.js, I've created a repository that parse/compile all the shaders to help with that. I also found another repository that does this in a more interactive way.
https://github.com/Jonathan-J8/three-materials-compiled.git

Thank you again to take the time to thought about it.
Best!

**Pull request closed without merging**
